name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    # Publishing

    - name: dotnet publish
      run: |
        cd src/ThemesOfDotNet
        dotnet publish -c Release -o '../../artifacts/ThemesOfDotNet'
        cd ../..

    # Deploy to Azure

    - name: webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: dotnetepics
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./artifacts/ThemesOfDotNet

